//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("TomatoTimer.UI")]
[assembly: AssemblyDescription("Tomato Timer User Interface")]
[assembly: AssemblyCompany("robcthegeek")]
[assembly: AssemblyProduct("Tomato Timer")]
[assembly: AssemblyCopyright("Copyright © robcthegeek 2010")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("5F275C9D-3CEA-4a03-AFC4-5CC5CD983643")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
