//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("TomatoTimer.Core")]
[assembly: AssemblyDescription("Tomato Timer Core")]
[assembly: AssemblyCompany("Leonis Software")]
[assembly: AssemblyProduct("Tomato Timer")]
[assembly: AssemblyCopyright("Copyright © Leonis Software 2009")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("fef52bf2-62a3-4cee-aa41-a541c20c0764")]
[assembly: AssemblyFileVersion("1.0.0.0")]


